### ISSUE TITLE
There is a formatting error in your example json file.

### ISSUE THREAD

**Issue by TheWangYang** [bairuofei/sampling_ltl_planning#1]
Sorry to bother you, there is a format error in your json file. As shown below.
![image](https://user-images.githubusercontent.com/48975488/161182163-7a37aa7e-52d4-4157-9239-10c9d96d6cf8.png)

**Comment by bairuofei** [comment]
Thank you for pointing it out. I have corrected this error.

**Comment by wwjzzz** [comment]
> 抱歉打扰您，您的json文件格式错误。如下所示。 ![图片](https://user-images.githubusercontent.com/48975488/161182163-7a37aa7e-52d4-4157-9239-10c9d96d6cf8.png)

Can you run it successfully? I met some question
